<?php $collection=$this->getProductPartDetails(); ?>
<?php $product=$this->getProduct();?>
<?php var_dump($product->getSoldCount())?>
<?php if($product->getSoldCount())
    {
        echo 'Sold Count : '.$product->getSoldCount();
    }
?>
<?php foreach ($collection->getData() as $result) {
    if ($result['mfr']): ?>
        <div class="mfr">
            <?php echo $this->__("Mfr :  {$result['mfr']}") ?>
        </div>
    <?php endif; ?>
    <?php if ($result['address']): ?>
        <div class="address">
            <?php echo $this->__("Address :  {$result['address']}") ?>
        </div>
    <?php endif; ?>
    <?php if ($result['avg_qty']): ?>
        <div class="avg_qty">
            <?php echo $this->__("Avarage Qty :  {$result['avg_qty']}") ?>
        </div>
    <?php endif; ?>
<?php } ?>